name: "Setup Surfpool"
description: "Installs and caches the Surfpool CLI"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      name: Cache Surfpool Binary
      id: cache-surfpool
      with:
        path: ~/.local/bin/surfpool
        key: surfpool-${{ runner.os }}-v${{ env.SURFPOOL_CLI_VERSION }}

    - shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: nick-fields/retry@v2
      if: steps.cache-surfpool.outputs.cache-hit != 'true'
      with:
        retry_wait_seconds: 300
        timeout_minutes: 2
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          set -euxo pipefail
          echo "Installing Surfpool version ${{ env.SURFPOOL_CLI_VERSION }}"
          mkdir -p "$HOME/.local/bin"
          curl -sL -o /tmp/surfpool.tar.gz "https://github.com/solana-foundation/surfpool/releases/download/v${{ env.SURFPOOL_CLI_VERSION }}/surfpool-linux-x64.tar.gz"
          tar -xzf /tmp/surfpool.tar.gz -C "$HOME/.local/bin"
          chmod +x "$HOME/.local/bin/surfpool"
          rm /tmp/surfpool.tar.gz

    - shell: bash
      run: surfpool -V

    

